name: MLOps Football Pipeline

on:
  push:
    branches:
      - main
  # Descomenta las líneas de abajo si quieres que corra automáticamente cada Viernes a las 12:00 UTC
  # schedule:
  #   - cron: '0 12 * * 5'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar Repositorio
      uses: actions/checkout@v4

    - name: Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: |
        python -bin/pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pipeline - Entrenar Modelo
      run: python src/train.py

    - name: Pipeline - Generar Predicciones
      run: python src/predict.py

    - name: Guardar Cambios Automáticos en GitHub
      run: |
        git config --local user.email "github-actions[bot]@github.com"
        git config --local user.name "github-actions[bot]"
        git add models/ data/ reporte_predicciones.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automated MLOps run: Model update and predictions" && git push)
